- hosts: mysql 
  user: root
  sudo: yes
  roles:
         - mysql
         - ufwbackend

- hosts: wordpress
  user: root
  sudo: yes
  roles:
        - php
        - nginx
        - ufwfront

- hosts: jenkins
  vars:
  roles:
        - ansible-java
        - jenkins
