---

 - copy:
    src: "{{ role_path }}/files/wordpress.dmp"
    dest: /tmp/wordpress.dmp
    owner: root
    group: root
    mode: 0755

 - name: Add repository for MySQL 5.6
   apt_repository: repo='ppa:ondrej/mysql-5.6'
  #  when: mysql_version == "5.6"

 - name: Install the MySQL packages
   apt: name={{ item }} state=installed update_cache=yes
   with_items:
     - mysql-server-5.6
     - mysql-client-5.6
     - python-mysqldb
     - libmysqlclient-dev

 - name: Update MySQL root password for all root accounts
   mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} state=present
   with_items:
     - "{{ ansible_hostname }}"
     - 0.0.0.0
     - ::1
     - localhost

 - name: Copy the root credentials as .my.cnf file
   template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

 - name: Ensure Anonymous user(s) are not in the database
   mysql_user: name='' host={{ item }} state=absent
   with_items:
     - localhost
     - "{{ ansible_hostname }}"

 - name: Copy the root credentials as .my.cnf file
   template: src=root.cnf.j1 dest=/etc/mysql/mysql.conf.d/mysqld.cnf mode=0600

 - mysql_user:
    name: wordpress
    password: rognarock
    host: '%'
    priv: '*.*:ALL'
    state: present

 - name: Restore database
   mysql_db:
     name: wordpress
     state: import
     target: /tmp/wordpress.dmp

 - name: Create database
   mysql_db: db=wordpress state=present


 - name: Remove the test database
   mysql_db: name=test state=absent
   notify:
     - Restart MySQL

 - name: restart mysql
   service: name=mysql
            enabled=yes
            state=restarted       
