- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: allow

- name: Set logging
  ufw:
    logging: on

- name: Run rules
  shell: |
       sudo ufw enable
       sudo ufw default deny incoming
       sudo ufw allow 22
       sudo ufw allow 80
       sudo ufw allow 443
