BOX_IMAGE = "bento/ubuntu-16.04"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.define "wordpress.local" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "wordpress.local"
    subconfig.vm.network :private_network, ip: "192.168.56.41"
    subconfig.vm.provision "file", source: "./server_ca.pub", destination: "~/.ssh/authorized_keys"
    subconfig.vm.provision "file", source: "./server_ca", destination: "/home/vagrant/server_ca"
    subconfig.vm.provision "shell", inline: <<-SHELL
    sudo mkdir /root/.ssh
    sudo chmod 700 /root/.ssh
    sudo cp /home/vagrant/.ssh/authorized_keys /root/.ssh/
    sudo apt-get update
    sudo apt-get -y install ntp
    SHELL

  end
config.vm.define "database.local" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "database.local"
    subconfig.vm.network :private_network, ip: "192.168.56.42"
    subconfig.vm.provision "file", source: "./server_ca.pub", destination: "~/.ssh/authorized_keys"
    subconfig.vm.provision "file", source: "./server_ca", destination: "/home/vagrant/server_ca"
    subconfig.vm.provision "shell", inline: <<-SHELL
    sudo mkdir /root/.ssh
    sudo chmod 700 /root/.ssh
    sudo cp /home/vagrant/.ssh/authorized_keys /root/.ssh/
    sudo apt-get update
    sudo apt-get -y install ntp
    SHELL
  end
config.vm.define "jenkins.local" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "jenkins.local"
    subconfig.vm.network :private_network, ip: "192.168.56.43"
    subconfig.vm.provision "file", source: "./server_ca.pub", destination: "~/.ssh/authorized_keys"
    subconfig.vm.provision "file", source: "./server_ca", destination: "/home/vagrant/server_ca"
    subconfig.vm.provision "shell", inline: <<-SHELL
    sudo mkdir /root/.ssh
    sudo chmod 700 /root/.ssh
    sudo cp /home/vagrant/.ssh/authorized_keys /root/.ssh/
    sudo apt-get update
    sudo apt-get -y install ntp
    SHELL
  end
 end
